# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tabi and Way
email: sudofree@163.com
description: >- # this means to ignore newlines until "baseurl:"
  Communication Engineering and Computer Science consist the content
  of this blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://iamhyc.github.io" # the base hostname & protocol for your site
keyword: sudo_free
twitter_username: iamhyc
github_username:  iamhyc

# Global Configuration
source: ./website
includes_dir: ./website/_includes
layouts_dir: ./website/_layouts
plugins_dir: ./website/_plugins
data_dir: ./website/_data
destination: ./github-pages
safe: True
timezone: Asia/Shanghai
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - batch/
  - docs/
  - server/
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
